# projects.toml file describing inputs for dream2nix
#
# To re-generate this file, run:
#   nix run .#detect-projects $source
# ... where `$source` points to the source of your project.
#
# If the local flake is unavailable, alternatively execute the app from the
# upstream dream2nix flake:
#   nix run github:nix-community/dream2nix#detect-projects $source

[tailforward]
name = "tailforward"
relPath = ""
subsystem = "rust"
translator = "cargo-lock"

[tailforward.subsystemInfo]
workspaceMembers = [ "tailforward-cfg",]
[[tailforward.subsystemInfo.crates]]
name = "tailforward"
relPath = ""
version = "0.3.0"

[[tailforward.subsystemInfo.crates]]
name = "tailforward-cfg"
relPath = "tailforward-cfg"
version = "0.1.0"

