# projects.toml file describing inputs for dream2nix
#
# To re-generate this file, run:
#   nix run .#detect-projects $source
# ... where `$source` points to the source of your project.
#
# If the local flake is unavailable, alternatively execute the app from the
# upstream dream2nix flake:
#   nix run github:nix-community/dream2nix#detect-projects $source

[ts_to_tg]
name = "ts_to_tg"
relPath = ""
subsystem = "rust"
translator = "cargo-lock"
translators = [ "cargo-lock", "cargo-toml",]

[ts_to_tg.subsystemInfo]
workspaceMembers = []
[[ts_to_tg.subsystemInfo.crates]]
name = "ts_to_tg"
relPath = ""
version = "0.1.0"

